### PR TITLE
#21708 address support for managers

### PR DESCRIPTION
**Pull request by danchr**

### CODE REVIEW

**Comment by cmoesgaard** [comment]
What about creating addresses for managers?

**Comment by danchr** [comment]
> What about creating addresses for managers?

I'm not sure I follow — what do you mean?

**Comment by cmoesgaard** [comment]
From what I can see, you've implemented editing addresses for managers, but it's not possible to actually create addresses, as part of the process of creating a manager.

**Comment by danchr** [comment]
@cmoesgaard Ping?

**Pull request merged**
